Add escape hatch to run arbitrary setup script
RalfG/python-wheels-manylinux-build pull request #12
Opened 2020-03-13 16:09 UTC by exarkun

Fixes #11

2020-03-17 14:13 UTC, RalfG requested changes
Great idea. Thanks for the PR!

I think `pre-build-script` would be a better name for the option, as it requires a full command, not just a list of requirements, such as `build-requirements` and `system-packages`. Can you implement the suggested changes, and additonally update `README.md` and `full_workflow_example.yml` accordingly? Thanks!

2020-03-17 14:13 UTC, RalfG commented on action.yml
> +  install-extra-requirements:
```suggestion
  pre-build-script:
```

2020-03-17 14:13 UTC, RalfG commented on action.yml
> +    - ${{ inputs.install-extra-requirements }}
```suggestion
    - ${{ inputs.pre-build-script }}
```

2020-03-17 14:13 UTC, RalfG commented on entrypoint.sh
> +INSTALL_EXTRA_REQUIREMENTS=$5
```suggestion
PRE_BUILD_SCRIPT=$5
```

2020-03-17 14:13 UTC, RalfG commented on entrypoint.sh
> +if [ ! -z "$INSTALL_EXTRA_REQUIREMENTS" ]; then
```suggestion
if [ ! -z "$PRE_BUILD_SCRIPT" ]; then
```

2020-03-17 14:13 UTC, RalfG commented on entrypoint.sh
> +    "$INSTALL_EXTRA_REQUIREMENTS"
```suggestion
    "$PRE_BUILD_SCRIPT" || { echo "Pre-build script failed."; exit 1; }
```

2020-03-17 14:28 UTC, exarkun commented
> I think pre-build-script would be a better name for the option, as it requires a full command, not just a list of requirements, such as build-requirements and system-packages. Can you implement the suggested changes, and additonally update README.md and full_workflow_example.yml accordingly? Thanks!

Thanks.  I think that is a better name, indeed.

Since I submitted the PR I went ahead and did some more testing of the changes for my project and I found I needed to make one further change - executing the pre-build script was not sufficient because I also needed to get a new directory into PATH for the build step (my use-case is installing the Rust `cargo` tool).

I fixed this by making the pre-build script get _sourced_ instead of executed so it can export environment changes to entrypoint.sh.  I'm not sure how sound this approach is, though.  I wonder if you have any thoughts on this requirement?

2020-03-19 09:09 UTC, RalfG commented
Exporting would be yet another option then, next to executing... But I noticed that there is no execution command (i.e. no `sh`) in front of the `"$PRE_BUILD_SCRIPT"` variable:

```
if [ ! -z "$PRE_BUILD_SCRIPT" ]; then
    "$PRE_BUILD_SCRIPT" || { echo "Pre-build script failed."; exit 1; }
fi
```

So instead of positioning this option as the path to a script, this could just be a custom command. In your case `pre-build-script: "source <path_to_script.sh>"` should work, right? For others this could be `sh <path_to_script.sh>`, or even a simple command, e.g. modifying an environment variable: `"CFLAGS=${CFLAGS//-pipe/}"`.

2020-07-14 11:54 UTC, RalfG approved these changes

2020-07-14 11:54 UTC, merged