Allow yum packages to be installed
RalfG/python-wheels-manylinux-build pull request #2
Opened 2020-02-03 19:47 UTC by dries007

Added `system-packages` property that gets passed to `yum install -y`.

This allows me to install libraries my C extention needs.

Another option would be to allow arbitrary commands before lauch, but I don't know what would be a good way of supporting that, so I did it this way.

2020-02-04 09:57 UTC, RalfG requested changes
Thanks for the addition of this option! Just a few things need to be changed for consistency and clarity between the options.
Can you also add the additional option and changes to README.md?

2020-02-04 09:57 UTC, RalfG commented on action.yml
>      description: 'Packages required at build time, space-separated'
For clarity, we should specify this option as "pip packages". This also needs to be changed in `README.md`
```suggestion
    description: 'pip packages required at build time, space-separated'
```

2020-02-04 09:57 UTC, RalfG commented on entrypoint.sh
> +fi
The option is called `system-packages` in action.yml. We should keep this naming consistent in the entrypoint.sh. `SYSTEM_REQUIREMENTS` should be changed to `SYSTEM_PACKAGES`.

2020-02-04 09:57 UTC, RalfG commented on entrypoint.sh
> +    yum install -y ${SYSTEM_REQUIREMENTS}
Can you also add an error message and exit code if the yum install failed?
```suggestion
    yum install -y ${SYSTEM_REQUIREMENTS}  || { echo "Installing yum package(s) failed."; exit 1; }
```

2020-02-04 12:10 UTC, dries007 commented
Will do

2020-02-05 19:22 UTC, dries007 commented
I made the suggested changes.

Just an FIY for anyone trying to find out what packages to include, it's easiest to spin up a docker instance with `docker run -it 'quay.io/pypa/manylinux1_x86_64' bash` and using `yum` from there.
Most of the online package databases have dropped support for the CentOS 6.

2020-02-06 12:12 UTC, RalfG approved these changes
Thanks!

2020-02-06 12:13 UTC, merged